apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: osi.borkenhagen@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          cloudDNS:
            project: cloud-porsche
            serviceAccountSecretRef:
              name: google-credentials
              key: key.json
