apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-porsche-com
  namespace: {{ .Release.Namespace}}
spec:
  secretName: cloud-porsche-com-tls
  issuerRef:
    name: cert-issuer
    kind: Issuer
  dnsNames:
    - {{ .Values.tenantId }}.cloud-porsche.com
