apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-porsche-com
  namespace: {{ .Release.Namespace }}
spec:
  secretName: cloud-porsche-com-tls
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.tenantId }}.cloud-porsche.com
  acme:
    config:
      - dns01:
          provider: dns
        domains:
          - {{ .Values.tenantId }}.cloud-porsche.com
