apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer
  namespace: {{ .Release.Namespace}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: osi.borkenhagen@gmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
        cloudDNS:
          project: cloud-porsche
