apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-porsche-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.proxySendTimeout | quote }}
    cert-manager.io/cluster-issuer: cert-issuer
spec:
  tls:
    - hosts:
        - {{ .Values.tenantId }}.cloud-porsche.com
      secretName: cloud-porsche-com-tls
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /property-management(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: property-management
                port:
                  number: {{ .Values.propertyManagement.port }}
          - path: /parking-management(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: parking-management
                port:
                  number: {{ .Values.parkingManagement.port }}
          - path: /monitoring-management(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: monitoring-management
                port:
                  number: {{ .Values.monitoringManagement.port }}

