apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-porsche-ingress
  namespace: {{ .Release.Namespace}}
  annotations:
    networking.gke.io/managed-certificates: property-management-cert,parking-management-cert,monitoring-management-cert
    kubernetes.io/ingress.class: gce
spec:
  ingressClassName: gce
  defaultBackend:
    service:
      name: property-management
      port:
        number: {{ .Values.propertyManagement.port }}
  rules:
    - host: property-management.{{ .Values.tenantId }}.cloud-porsche.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: property-management
                port:
                  number: {{ .Values.propertyManagement.port }}
    - host: parking-management.{{ .Values.tenantId }}.cloud-porsche.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parking-management
                port:
                  number: {{ .Values.parkingManagement.port }}
    - host: monitoring-management.{{ .Values.tenantId }}.cloud-porsche.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitoring-management
                port:
                  number: {{ .Values.monitoringManagement.port }}
