apiVersion: v1
kind: Service
metadata:
  name: monitoring-management
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - name: {{ .Values.monitoringManagement.port | quote }}
      port: {{ .Values.monitoringManagement.port }}
      targetPort: {{ .Values.monitoringManagement.port }}
  type: NodePort
  selector:
    name: monitoring-management
