apiVersion: v1
kind: Service
metadata:
  name: parking-management
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - name: {{ .Values.parkingManagement.port | quote }}
      port: {{ .Values.parkingManagement.port }}
      targetPort: {{ .Values.parkingManagement.port }}
  type: LoadBalancer
  selector:
    name: parking-management
