apiVersion: apps/v1
kind: Deployment
metadata:
  name: property-management
  namespace: {{ .Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: property-management
  template:
    metadata:
      labels:
        name: property-management
    spec:
      containers:
        - env:
            - name: FIREBASE_PROJECT_ID
              value: cloud-porsche
            - name: FIREBASE_STORAGE_BUCKET
              value: {{ .Values.propertyManagement.envs.FIREBASE_STORAGE_BUCKET }}
            - name: FIRESTORE_DB
              value: {{ .Values.propertyManagement.envs.FIRESTORE_DB }}
            - name: CORS_ORIGINS
              value: {{ .Values.sharedEnvs.CORS_ORIGINS }}
            - name: FIREBASE_OVERWRITE_CREDENTIALS
              value: {{ .Values.sharedEnvs.FIREBASE_OVERWRITE_CREDENTIALS | quote }}
            - name: FIREBASE_CLIENT_EMAIL
              value: {{ .Values.secrets.FIREBASE_CLIENT_EMAIL }}
            - name: FIREBASE_PRIVATE_KEY
              value: {{ .Values.secrets.FIREBASE_PRIVATE_KEY | quote }}
            - name: FIREBASE_TOKEN
              value: {{ .Values.secrets.FIREBASE_TOKEN }}
            - name: PORT
              value: {{ .Values.propertyManagement.port | quote }}
            - name: MONITORING_QUEUE
              value: {{ .Values.propertyManagement.envs.MONITORING_QUEUE }}
          image: {{ .Values.images.propertyManagement }}
          imagePullPolicy: IfNotPresent
          name: property-management
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.propertyManagement.port }}
              protocol: TCP
          {{- if .Values.propertyManagement.livelinessProbe }}
          livenessProbe:
            httpGet:
              port: {{ .Values.propertyManagement.port }}
              path: /v1/
          readinessProbe:
            httpGet:
              port: {{ .Values.propertyManagement.port }}
              path: /v1/
          {{- end }}
      restartPolicy: Always
