apiVersion: v1
kind: Service
metadata:
  name: property-management
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - name: {{ .Values.propertyManagement.port | quote }}
      port: {{ .Values.propertyManagement.port }}
      targetPort: {{ .Values.propertyManagement.port }}
  type: LoadBalancer
  selector:
    name: property-management
