tenantId: ${TENANT_ID}

resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

propertyManagement:
  envs:
    FIREBASE_STORAGE_BUCKET: property-management-${TENANT_ID}
    FIRESTORE_DB: property-management-${TENANT_ID}
    MONITORING_QUEUE: ${TENANT_ID}-queue
parkingManagement:
  envs:
    FIREBASE_STORAGE_BUCKET: property-management-${TENANT_ID}
    FIRESTORE_DB: property-management-${TENANT_ID}
    PROPERTY_MANAGEMENT_API_URL: http://property-management:8080
    MONITORING_QUEUE: ${TENANT_ID}-queue
monitoringManagement:
  envs:
    FIRESTORE_DB: monitoring-${TENANT_ID}
    QUEUE_SUBSCRIPTION: ${TENANT_ID}-subscription
