resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 1024Mi

propertyManagement:
  envs:
    FIREBASE_STORAGE_BUCKET: property-management-${TENANT_ID}
    FIRESTORE_DB: property-management-${TENANT_ID}
parkingManagement:
  envs:
    FIREBASE_STORAGE_BUCKET: property-management-${TENANT_ID}
    FIRESTORE_DB: property-management-${TENANT_ID}
monitoringManagement:
  envs:
    FIRESTORE_DB: monitoring-${TENANT_ID}
