tenantId: enteprise-6y33t-staging

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

propertyManagement:
  envs:
    FIREBASE_STORAGE_BUCKET: property-management-enteprise-6y33t-staging
    FIRESTORE_DB: property-management-enteprise-6y33t-staging
    MONITORING_QUEUE: enteprise-6y33t-staging-queue
parkingManagement:
  envs:
    FIREBASE_STORAGE_BUCKET: property-management-enteprise-6y33t-staging
    FIRESTORE_DB: property-management-enteprise-6y33t-staging
    PROPERTY_MANAGEMENT_API_URL: http://property-management:8080
    MONITORING_QUEUE: enteprise-6y33t-staging-queue
monitoringManagement:
  envs:
    FIRESTORE_DB: monitoring-enteprise-6y33t-staging
    QUEUE_SUBSCRIPTION: enteprise-6y33t-staging-subscription
