# Default values for default.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  propertyManagement: cloud-porsche/property-management:latest
  parkingManagement: cloud-porsche/parking-management:latest
  monitoringManagement: cloud-porsche/monitoring-management:latest

certs:
  - property-management
  - parking-management
  - monitoring-management

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

#This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled:
    - property-management
    - parking-management
    - monitoring-management
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

sharedEnvs:
  FIREBASE_OVERWRITE_CREDENTIALS: true
  CORS_ORIGINS: https://cloud-porsche.github.io,https://cloud-dev.ostabo.com,http://localhost:3000

propertyManagement:
  port: 8080
  livelinessProbe: true
  envs:
    FIREBASE_STORAGE_BUCKET: cloud-porsche-staging
    FIRESTORE_DB: staging
    MONITORING_QUEUE: monitoring-queue
parkingManagement:
  port: 8084
  livelinessProbe: true
  envs:
    FIREBASE_STORAGE_BUCKET: cloud-porsche-staging
    FIRESTORE_DB: staging
    PROPERTY_MANAGEMENT_API_URL: http://property-management:8080
    MONITORING_QUEUE: monitoring-queue
monitoringManagement:
  port: 8083
  livelinessProbe: true
  envs:
    FIRESTORE_DB: monitoring-staging
    QUEUE_SUBSCRIPTION: monitoring-subscription
