name: cloud-porsche-management

networks:
  cloud-porsche:
    driver: bridge

services:
  ui:
    image: cloud-porsche-ui
    build:
      context: .
      dockerfile: ./cloud-dev-ui/Dockerfile
      args:
        - VITE_PROPERTY_MANAGEMENT_API_URL=http://localhost:8080
        - VITE_PROPERTY_MANAGEMENT_API_OPTIONS=http://localhost:8080,https://cloud-property-management.ostabo.com,https://property-management-c4okt5o2kq-ez.a.run.app
    ports:
      - "3000:80"
    networks:
      - cloud-porsche
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
  property-management:
    image: cloud-porsche-management
    build:
      context: .
      dockerfile: ./cloud-dev-property-management/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CORS_ORIGIN=localhost
      - FIRESTORE_EMULATOR_HOST=
      - FIREBASE_OVERWRITE_CREDENTIALS=true
    env_file:
      - ./cloud-dev-property-management/.env
    networks:
      - cloud-porsche
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/v1/" ]
