name: cloud-porsche-management

volumes:
  cloud-dev-property-management-db:

services:
  ui:
    image: cloud-porsche-ui
    build:
      context: .
      dockerfile: ./cloud-dev-ui/Dockerfile
      args:
        - VITE_PROPERTY_MANAGEMENT_API_URL=${VITE_PROPERTY_MANAGEMENT_API_URL}
        - VITE_PROPERTY_MANAGEMENT_API_OPTIONS=${VITE_PROPERTY_MANAGEMENT_API_OPTIONS}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
  property-management:
    image: cloud-porsche-management
    build:
      context: .
      dockerfile: ./cloud-dev-property-management/Dockerfile
    volumes:
      - cloud-dev-property-management-db:/db/
    environment:
      - PORT=8080
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_ORIGINS=${CORS_ORIGINS}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/v1/" ]
