name: cloud-porsche-management

networks:
  cloud-porsche:

services:
  ui:
    image: cloud-porsche-ui
    build:
      context: .
      dockerfile: ./cloud-dev-ui/Dockerfile
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN:-https://cloud-porsche.firebaseapp.com}
        - VITE_PROPERTY_MANAGEMENT_API_URL=${VITE_PROPERTY_MANAGEMENT_API_URL}
        - VITE_PROPERTY_MANAGEMENT_API_OPTIONS=${VITE_PROPERTY_MANAGEMENT_API_OPTIONS}
        - VITE_DISABLE_OAUTH_GITHUB=${VITE_DISABLE_OAUTH_GITHUB}
        - VITE_DISABLE_OAUTH_GOOGLE=${VITE_DISABLE_OAUTH_GOOGLE}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
  property-management:
    image: cloud-porsche-management
    build:
      context: .
      dockerfile: ./cloud-dev-property-management/Dockerfile
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - PORT=${PORT:-8080}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - FIREBASE_PROJECT_ID=${FIREBASE_STORAGE_BUCKET:-cloud-porsche}
      - FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST}
      - FIREBASE_STORAGE_EMULATOR_HOST=${FIREBASE_STORAGE_EMULATOR_HOST}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-cloud-porsche-staging}
      - FIREBASE_OVERWRITE_CREDENTIALS=${FIREBASE_OVERWRITE_CREDENTIALS:-true}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIRESTORE_DB=${FIRESTORE_DB:-staging}
    restart: unless-stopped
    networks:
      - cloud-porsche
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/v1/" ]
