/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDefectPopup: typeof import('./components/AddDefectPopup.vue')['default'];
    AppFooter: typeof import('./components/AppFooter.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SearchFilter: typeof import('./components/SearchFilter.vue')['default'];
    StatusChip: typeof import('./components/StatusChip.vue')['default'];
  }
}
