/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDefectPopup: typeof import('./components/AddDefectPopup.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CounterCard: typeof import('./components/CounterCard.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    PaidFeature: typeof import('./components/PaidFeature.vue')['default']
    ParkingSpotComponent: typeof import('./components/ParkingSpotComponent.vue')['default']
    ProTier: typeof import('./components/ProTier.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./components/SearchFilter.vue')['default']
    StatusChip: typeof import('./components/StatusChip.vue')['default']
  }
}
