/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/[tenantId]/': RouteRecordInfo<'/[tenantId]/', '/:tenantId', { tenantId: ParamValue<true> }, { tenantId: ParamValue<false> }>,
    '/[tenantId]/defects/[id]': RouteRecordInfo<'/[tenantId]/defects/[id]', '/:tenantId/defects/:id', { tenantId: ParamValue<true>, id: ParamValue<true> }, { tenantId: ParamValue<false>, id: ParamValue<false> }>,
    '/[tenantId]/monitoring': RouteRecordInfo<'/[tenantId]/monitoring', '/:tenantId/monitoring', { tenantId: ParamValue<true> }, { tenantId: ParamValue<false> }>,
    '/[tenantId]/profile': RouteRecordInfo<'/[tenantId]/profile', '/:tenantId/profile', { tenantId: ParamValue<true> }, { tenantId: ParamValue<false> }>,
    '/[tenantId]/property/': RouteRecordInfo<'/[tenantId]/property/', '/:tenantId/property', { tenantId: ParamValue<true> }, { tenantId: ParamValue<false> }>,
    '/[tenantId]/property/[id]': RouteRecordInfo<'/[tenantId]/property/[id]', '/:tenantId/property/:id', { tenantId: ParamValue<true>, id: ParamValue<true> }, { tenantId: ParamValue<false>, id: ParamValue<false> }>,
    '/[tenantId]/settings': RouteRecordInfo<'/[tenantId]/settings', '/:tenantId/settings', { tenantId: ParamValue<true> }, { tenantId: ParamValue<false> }>,
  }
}
