apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-porsche
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /v1/*
            pathType: Prefix
            backend:
              service:
                name: property-management
                port:
                  number: 80
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80

