name: Terraform destroy
on: workflow_dispatch
jobs:
  tf-destroy:
    #if: github.ref == 'refs/heads/develop'
    name: Terraform destroy 🏗️
    runs-on: ubuntu-22.04
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - uses: devkeydet/action-environment-queue@v1
        with:
          environment: cloud-porsche-terraform
          github-token: ${{ secrets.A_GITHUB_TOKEN }}
          timeout: 2000000
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'cloud-porsche'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
      - name: Terraform init
        working-directory: ./tf
        run: terraform init -input=false
      - name: Terraform destroy
        working-directory: ./tf
        run: terraform destroy -input=false -compact-warnings -auto-approve -var firebase_token=${{ secrets.FIREBASE_TOKEN }}
