name: Terraform Create Tenant
on:
  workflow_dispatch:
    inputs:
      tenant_id:
        type: string
        description: 'Tenant ID'
        required: true
      tenant_type:
        type: choice
        default: 'enterprise'
        options:
          - free
          - pro
          - enterprise
        description: 'Type of tenant (e.g. pricing plan); free, pro, or enterprise'
jobs:
  tf-tenant-create:
    #if: github.ref == 'refs/heads/develop'
    name: Terraform create tenant 🚮
    runs-on: ubuntu-22.04
    permissions:
      id-token: 'write'
      contents: 'write'
    steps:
      - uses: devkeydet/action-environment-queue@v1
        with:
          environment: cloud-porsche-terraform
          github-token: ${{ secrets.A_GITHUB_TOKEN }}
          timeout: 2000000
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'cloud-porsche'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
      - uses: danielr1996/envsubst-action@1.0.0
        env:
          TENANT_ID: ${{ inputs.tenant_id }}
        with:
          input: ./tf/${{ inputs.tenant_type }}-tenant.template
          output: ./tf/${{ inputs.tenant_id }}.tf
      - uses: danielr1996/envsubst-action@1.0.0
        env:
          TENANT_ID: ${{ inputs.tenant_id }}
        with:
          input: ./k8s/helm/cloud-porsche-default/${{ inputs.tenant_type }}-template.yaml
          output: ./k8s/helm/cloud-porsche-default/values-${{ inputs.tenant_id }}.yaml
      - name: Terraform init
        working-directory: ./tf
        run: terraform init -input=false
      - name: Terraform create tenant
        working-directory: ./tf
        run: |
          terraform apply \
              -input=false \
              -compact-warnings \
              -auto-approve \
              -var firebase_token=${{ secrets.FIREBASE_TOKEN }}
      - name: Delete on Terraform fail
        if: failure()
        working-directory: ./tf
        run: |
          terraform destroy \
              -target helm.${{ inputs.tenant_id }} \
              -target module.${{ inputs.tenant_id }} \
              -input=false \
              -compact-warnings \
              -auto-approve \
              -var firebase_token=${{ secrets.FIREBASE_TOKEN }}
      - name: Commit and push changes
        run: |
          git config --global user.name 'Tenant Creation Bot'
          git config --global user.email 'tenant-bot@noreply.com'
          git pull --rebase --strategy-option=theirs
          git add ./tf/${{ inputs.tenant_id }}.tf ./k8s/helm/cloud-porsche-default/values-${{ inputs.tenant_id }}.yaml
          git commit -am "Created tenant: ${{ inputs.tenant_id }}"
          git push
