name: Deploy website

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js you need

      # Step 3: Change working directory and install pnpm
      - name: Install pnpm
        working-directory: ./cloud-dev-ui  # Change working directory to ./cloud-dev-ui
        run: npm install -g pnpm

      - name: Build types
        working-directory: ./cloud-dev-types
        run: pnpm run build

      - name: Link Types
        working-directory: ./cloud-dev-ui
        run: pnpm link-types

      # Step 4: Install dependencies using pnpm in the working directory
      - name: Install dependencies
        working-directory: ./cloud-dev-ui  # Change working directory to ./cloud-dev-ui
        run: pnpm install

      # Step 5: Build the project in the working directory
      - name: Build project
        working-directory: ./cloud-dev-ui  # Change working directory to ./cloud-dev-ui
        run: pnpm build  # Adjust the build command if necessary (e.g., pnpm run build)

      # Step 6: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/develop'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cloud-dev-ui/dist  # Use the correct path for the build output
