name: Build & Deploy 🚀

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    env:
      VITE_BASE_URL: /cloud-porsche
      VITE_PROPERTY_MANAGEMENT_API_URL: https://cloud-porsche-backend-319164640160.europe-west1.run.app
    steps:
    - uses: actions/checkout@v3
    - id: Build-Vue
      uses: nvkomata/VuePagesAction@1.1
      with:
        username: 'cloud-porsche'
        reponame: 'cloud-porsche'
        token: ${{ secrets.GITHUB_TOKEN }}
